apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"argoproj.io/v1alpha1","kind":"Application","metadata":{"annotations":{},"name":"backend-prod","namespace":"argocd"},"spec":{"destination":{"namespace":"default","server":"https://kubernetes.default.svc"},"project":"default","source":{"path":"deploy/overlays/prod","repoURL":"https://github.com/jamartinezv2023/schollar-backend.git","targetRevision":"main"},"syncPolicy":{"automated":{"prune":true,"selfHeal":true}}}}
  creationTimestamp: "2026-01-31T22:59:42Z"
  generation: 326
  name: backend-prod
  namespace: argocd
  resourceVersion: "34208"
  uid: a52d9dbd-33ee-4b48-9039-eec4dca81fda
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: deploy/overlays/prod
    repoURL: https://github.com/jamartinezv2023/schollar-backend.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
status:
  conditions:
  - lastTransitionTime: "2026-02-02T14:20:50Z"
    message: |-
      Failed to load target state: failed to generate manifest for source 1 of 1: rpc error: code = Unknown desc = `kustomize build <path to cached source>/deploy/overlays/prod` failed exit status 1: # Warning: 'commonLabels' is deprecated. Please use 'labels' instead. Run 'kustomize edit fix' to update your Kustomization automatically.
      Error: no resource matches strategic merge patch "ConfigMap.v1.[noGrp]/backend-config.[noNs]": no matches for Id ConfigMap.v1.[noGrp]/backend-config.[noNs]; failed to find unique target for patch ConfigMap.v1.[noGrp]/backend-config.[noNs]
    type: ComparisonError
  controllerNamespace: argocd
  health:
    lastTransitionTime: "2026-01-31T22:59:43Z"
    status: Healthy
  operationState:
    finishedAt: "2026-02-02T14:11:33Z"
    message: |-
      ComparisonError: Failed to load target state: failed to generate manifest for source 1 of 1: rpc error: code = Unknown desc = Manifest generation error (cached): `kustomize build <path to cached source>/deploy/overlays/prod` failed exit status 1: # Warning: 'commonLabels' is deprecated. Please use 'labels' instead. Run 'kustomize edit fix' to update your Kustomization automatically.
      Error: no resource matches strategic merge patch "ConfigMap.v1.[noGrp]/backend-config.[noNs]": no matches for Id ConfigMap.v1.[noGrp]/backend-config.[noNs]; failed to find unique target for patch ConfigMap.v1.[noGrp]/backend-config.[noNs]
    operation:
      initiatedBy:
        username: admin
      retry:
        backoff:
          duration: 5s
          factor: 2
          maxDuration: 3m0s
        limit: 2
      sync:
        dryRun: true
        prune: true
        revision: afb7f6a70a221f5729267a36c1997abeb259f5d1
        source:
          path: deploy/overlays/prod
          repoURL: https://github.com/jamartinezv2023/schollar-backend.git
          targetRevision: main
        syncOptions:
        - Validate=false
        - PruneLast=true
        - RespectIgnoreDifferences=true
        - CreateNamespace=true
        - ApplyOutOfSyncOnly=true
        - ServerSideApply=true
        - Replace=true
        syncStrategy:
          apply:
            force: true
    phase: Error
    retryCount: 2
    startedAt: "2026-02-02T14:11:32Z"
    syncResult:
      revision: ""
      source:
        path: deploy/overlays/prod
        repoURL: https://github.com/jamartinezv2023/schollar-backend.git
        targetRevision: main
  reconciledAt: "2026-02-02T14:22:18Z"
  resourceHealthSource: appTree
  sourceHydrator: {}
  summary: {}
  sync:
    comparedTo:
      destination:
        namespace: default
        server: https://kubernetes.default.svc
      source:
        path: deploy/overlays/prod
        repoURL: https://github.com/jamartinezv2023/schollar-backend.git
        targetRevision: main
    revision: main
    status: Unknown
